name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - pipeline/eslint

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Testing backend
        run: |
          cd backend
          npm install
          npm run dev

      - name: Install dependencies
        run: |
          cd frontend
          npm install
          npm start


  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install ESLint and Dependencies
        run: |
          cd frontend
          npm install
          npm run lint

      - name: Run ESLint on backend
        run: |
          cd backend
          npm install
          npm run lint
